### ISSUE TITLE
windows version bug

### ISSUE THREAD

**Issue by ephraimzki** [anandnet/Harmony-Music#241] opened 2024-06-28 03:11 UTC
There are 2 recommended albums in the home tab and I think it's a bug. Thanks

**Comment by JuniorMoreno86** [comment] 2024-06-28 03:32
Muy bien gracias

**Comment by anandnet** [comment] 2024-07-10 17:33
@ephraimzki  its not a bug, i believe you have set discover content "Based on last interaction". it populates based on your last interaction/ last song which was clicked to play.  for now i'm closing this, if case is different than this, you can reopen this.

**Closed by anandnet** 2024-07-10 17:33 UTC
