### ISSUE TITLE
Notification's seek bar is black

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#80] opened 2023-11-14 07:24 UTC
Whenever i play songs notification's seekbar is black means we can't see song progress. It's happening in all songs 
Device : Samsung galaxy j8
Android 10

![Screenshot_20231114-125337_1DM](https://github.com/anandnet/Harmony-Music/assets/90886938/00b96776-ee1d-48e6-b1ff-12174c5c9075)

**Comment by anandnet** [comment] 2023-11-17 08:34
Duplicate of #24

**Closed by anandnet** 2023-11-17 08:34 UTC
Labels: bug
